#!/bin/sh
cd $(dirname $0)
TREE_TOP=../..
export LD_LIBRARY_PATH=/lib
export LD_PRELOAD=/lib/libpthread.so.0

CMD="./exchange-tls12"
#CMD="gdb --args ./exchange-tls12"

${CMD} \
 -s -p $TREE_TOP/certstore/trusted \
 -b $TREE_TOP/certstore/trusted/homut_bundle.crt \
 -f $TREE_TOP/certstore/personal/homut_server.crt \
 -k $TREE_TOP/certstore/privkeys/homut_server.key

