#!/bin/sh
cd $(dirname $0)
cd ..
TREE_TOP=${PWD}
CERTSTORE=$TREE_TOP/certstore
SCRIPTS=$TREE_TOP/scripts
BIN_DIR=/usr/bin
EX_DIR=$TREE_TOP/client-server

export LD_LIBRARY_PATH=/lib
export LD_PRELOAD=/lib/libpthread.so.0

CMD_EX="${EX_DIR}/exchange-tls12"

${CMD_EX} -C $1 -e ateccx08
#gdb --args ${CMD_EX} -C $1 -e ateccx08

